language: python
python:
 - "2.7"
branches:
 only:
  - develop-microservice-blue
  - "/develop-microservice-blue-.+/"
install:
 - pip install waitress
 - pip install msgpack
 - pip install falcon
script:
 - nohup ./server/__init__.py &
 - sleep 4
after_script:
 - ./test_blue