language: node_js
node_js:
 - '10'
sudo: required
dist: trusty
branches:
 only:
 - develop-client-rhino
 - "/develop-client-rhino-.+/"
install:
 - ng lint
 - npm install
before_script:
 - npm install -g @angular/cli
script:
 - npm run build:prod