language: python
python:
 - "2.7"
branches:
 only:
  - develop-microservice-blue
  - "/develop-microservice-blue-.+/"
install:
 - pip install waitress
 - pip install msgpack
 - pip install falcon
before_script:
 - chmod +x ./test_blue
 - chmod +x ./server/__init__.py
script:
 - ./server/__init__.py &
 - sleep 4
after_script:
 - ./test_blue