language: python
python:
 - "2.7"
branches:
 only:
  - develop-microservice-blue
  - "/develop-microservice-blue-.+/"
install:
  - pip install waitress
# command to run tests
before_script:
 - cd ./server
script:
  - waitress-serve --port=8000 server.app:api 
after_script:
  - ./test_blue