apiVersion: apps/v1
kind: Deployment
metadata:
  name: purple-microservice
  timestamp: {currentdate}
spec:
  selector:
    matchLabels:
      app: purple-ms
  replicas: 15
  template:
    metadata:
      labels:
        app: purple-ms
    spec:
      containers:
      - name: purple-ms
        imagePullPolicy: Always
        image: sanjeevni/purple
        ports:
        - containerPort: 3000
